<script setup lang="ts">
import { BadgeCheck, Building2, FileText, Languages, Microscope, ShieldCheck } from '@lucide/vue'
useSeoMeta({ title: 'О клинике Жуйкан в Хэйхэ', description: 'Информация о стоматологической клинике Жуйкан: технологии, сопровождение, документы и гарантии лечения.' })
const facts = [
  { icon: Building2, title: 'Официальная клиника', text: 'Лицензионные сведения и перевод документов публикуются после проверки оригиналов.' },
  { icon: Microscope, title: 'Современная диагностика', text: 'План лечения строится на результатах осмотра и необходимых снимков.' },
  { icon: Languages, title: 'Русскоязычное сопровождение', text: 'Координатор помогает пациенту понимать решения врача и порядок лечения.' },
  { icon: ShieldCheck, title: 'Условия гарантии', text: 'Фиксируются для выбранного вида лечения и материалов.' },
]
</script>

<template>
  <main><PageHero eyebrow="О клинике" title="Современная стоматология с понятным подходом" text="На этой странице будут собраны проверяемые сведения о клинике, оборудовании, врачах, лицензиях и условиях лечения." /><section class="px-5 py-12 md:px-8 lg:px-12 lg:py-24"><div class="mx-auto max-w-[1440px]"><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><article v-for="fact in facts" :key="fact.title" class="rounded-[1.75rem] border border-ink/8 bg-white p-7"><component :is="fact.icon" class="size-7 text-brand" /><h2 class="mt-10 text-xl font-bold">{{ fact.title }}</h2><p class="mt-3 text-sm leading-6 text-ink/52">{{ fact.text }}</p></article></div><div class="mt-16 grid overflow-hidden rounded-[2.5rem] bg-ink text-white lg:grid-cols-2"><div class="p-7 md:p-12 lg:p-16"><p class="text-xs font-extrabold uppercase tracking-[.2em] text-[#aebaff]">Документы</p><h2 class="mt-5 text-4xl font-semibold tracking-[-.05em] md:text-5xl">Показываем подтверждения, а не значки доверия</h2><p class="mt-6 leading-8 text-white/55">В финальной версии здесь размещаются читаемые сканы лицензий, переводы, сведения о выдаваемых пациенту документах и реальные условия гарантии.</p></div><div class="grid gap-4 bg-white/5 p-7 md:p-12"><div v-for="item in ['Лицензия на медицинскую деятельность', 'Перевод лицензии на русский язык', 'Документы пациента после лечения', 'Условия гарантии по видам работ']" :key="item" class="flex items-center gap-4 rounded-2xl border border-white/10 p-5"><FileText class="size-6 text-[#aebaff]" /><span class="font-semibold">{{ item }}</span><BadgeCheck class="ml-auto size-5 text-white/30" /></div></div></div><div class="mt-16"><SectionHeading eyebrow="Фотографии" title="Увидеть клинику до поездки" text="Фасад, ресепшен, кабинеты, оборудование и лаборатория будут представлены только реальными фотографиями Жуйкан." /><div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div v-for="label in ['Фасад клиники', 'Ресепшен', 'Стоматологический кабинет', 'Оборудование', 'Лаборатория', 'Зона ожидания']" :key="label" class="group grid aspect-[4/3] place-items-center rounded-[1.75rem] border border-dashed border-brand/25 bg-mist"><div class="text-center"><Building2 class="mx-auto size-8 text-brand/35" /><p class="mt-3 text-sm font-bold text-brand">{{ label }}</p><p class="mt-1 text-xs text-ink/35">Место для реальной фотографии</p></div></div></div></div></div></section><RequestSection /></main>
</template>
