<script setup lang="ts">
import { CircleAlert, FileCheck2 } from '@lucide/vue'
import { services } from '~/data/content'
useSeoMeta({ title: 'Цены на лечение зубов в Хэйхэ | Жуйкан', description: 'Как формируется стоимость имплантации, протезирования и лечения зубов в клинике Жуйкан. Расчёт по снимку до поездки.' })
</script>

<template>
  <main><PageHero eyebrow="Цены" title="Стоимость, которую можно обсудить заранее" text="Предварительный бюджет рассчитывается по снимку. Финальная сумма зависит от диагностики, материалов и выбранного плана лечения." /><section class="px-5 py-12 md:px-8 lg:px-12 lg:py-20"><div class="mx-auto max-w-[1200px]"><div class="overflow-hidden rounded-[2rem] border border-ink/8 bg-white"><div class="grid grid-cols-[1fr_auto] bg-ink px-6 py-5 text-sm font-bold text-white md:px-8"><span>Направление</span><span>Ориентир</span></div><div v-for="service in services" :key="service.slug" class="grid grid-cols-[1fr_auto] gap-5 border-b border-ink/8 px-6 py-6 last:border-0 md:px-8"><div><NuxtLink :to="`/services/${service.slug}`" class="text-lg font-bold hover:text-brand">{{ service.title }}</NuxtLink><p class="mt-1 text-sm text-ink/45">{{ service.duration }}</p></div><p class="text-right font-bold text-brand">{{ service.price }}</p></div></div><div class="mt-6 flex items-start gap-3 rounded-2xl bg-mist p-5 text-sm leading-6 text-ink/60"><CircleAlert class="mt-0.5 size-5 shrink-0 text-brand" />Конкретные цены будут опубликованы после письменного подтверждения клиникой. Это защищает пациентов от устаревшей или неточной информации.</div><div class="mt-16 grid gap-4 md:grid-cols-3"><article v-for="item in ['Состояние зубов и костной ткани', 'Выбранные материалы и система', 'Количество этапов и визитов']" :key="item" class="rounded-[1.5rem] border border-ink/8 p-6"><FileCheck2 class="size-6 text-brand" /><h2 class="mt-8 text-xl font-bold">{{ item }}</h2><p class="mt-3 text-sm leading-6 text-ink/50">Эти данные врач учитывает при подготовке персонального плана лечения.</p></article></div></div></section><RequestSection /></main>
</template>
